on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  code-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Errors
        if: failure()
        run: |
          echo "Code scanning error detected. Disabling pull request."
          exit 1

      - name: Additional Check
        if: steps.code-scanning.outputs.ERROR_DETECTED == 'true'
        run: |
          echo "Additional error detected. Disabling pull request."
          exit 1
